### ISSUE TITLE
segmentation faulting with mayavi

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-library#36]
Just reporting on some odd behaviour that has kept me from getting any work done this morning: 

I'm running tvb in a virtualenv as-per tvb-pack/scripts on ubuntu 14.04. 

Basically I installed mayavi and all hell broke loose. 

Principally: calling

```python
from tvb.simulator.lab import *
```
caused python to crash with a segmentation fault. 

I didn't initially know what the problem was and ended up uninstalling and re-installing numpy and scipy, which is never a great idea. Eventually I traced the problem down to the `from plotting.tools import *` command in lab.py, and inside there to `from mayavi  import mlab`.

Incidentally, there seems to be a strange interaction with matplotlib. 

If I start python I can do 
```python
from mayavi import mlab
```

...but then doing
````python
from matplotlib import pylab
```
fails


Likewise, when I do vice-versa; 

```python
from matplotlib import pyplot
from mayavi import mlab
```
I get a segmentation fault. 

So in the end the solution was to uninstall mayavi, as I don't desperately need that it right now. 

At least now I can import from `tvb.simulator.lab`


Thought I would just note this down, in case it is useful to people. 


j

**Comment by maedoc** [comment]
I'm marking this is as closed because it's not TVB's fault.
