### ISSUE TITLE
Refactor history out of simulator

### ISSUE THREAD

**Issue by maedoc** [the-virtual-brain/tvb-library#38]
The computation of delayed state data is currently hard coded in the the simulator implementation, and should be factored out into a history module where multiple implementations shall be provided (dense, sparse, etc.). 

The interface for a history implementation will look something like

```python
class IHistory:

    def update(self, time: float, state: ndarray):
        pass

    def query(self, time: float) -> ndarray:
        pass
```

In the current implementation, the history is backed by a buffer, and updates & queries are not interpolated wrt. time, but nearest. For more advanced cases, such as local connectivity with delays, it will be imperative to have interpolation wrt. time, hence the use of time and not sample / index / step.

**Comment by i-Zaak** [comment]
There are multiple ways, how to approach this: we can either have the history completely separate, or bundle it (somehow) together with coupling. Motivation for this can be possibly getting rid of the ugly (nodes x cvar x nodes x modes) `delayed_state` array, which is exchanged between history and coupling function. 

For me it makes sense to hide this as an implementation detail of particular history class, have the coupling instance as an attribute of history, and query the history for the `node_coupling` and `local_coupling` vectors which then continue to the integration scheme. 

In fact, this class could be used to get rid of the `if surface` branching in the simulator `__call__` function. Which would be great :)
