### ISSUE TITLE
Fix coupling functions transpose

### ISSUE THREAD

**Issue by maedoc** [the-virtual-brain/tvb-library#43]
As noted in #41 coupling functions don't transpose the connectivity correctly, resulting in application of an effectively transposed delay matrix.

**Comment by timpx** [comment]
It seems to me, after careful check between Matlab code and TVB, that this also affects symmetric matrices. The solution that you propose fixed it.

**Comment by maedoc** [comment]
This is being tracked/fixed in JIRA/SVN

http://req.thevirtualbrain.org/browse/TVB-1729
