### ISSUE TITLE
CUDA implementation of Brunel-Wang model

### ISSUE THREAD

**Issue by i-Zaak** [the-virtual-brain/tvb-library#45]
Brunel-Wang model contains lookup tables, where a precomputed integral is used in the model's dfun. Instead of evaluating the integral at each call, the integral is precomputed for all values and put in a lookup table. When calling dfun, an interpolation is performed. This is terrible for GPUs, [see here](https://github.com/the-virtual-brain/tvb-library/blob/trunk/contrib/simulator/models/brunel_wang.py#L602). Special treatment suggested by @maedoc -- fitting polynomial or sin basis functions, detailed inspection of the actual integral shapes is however required. Such optimization should be of course also backed by tests...

**Comment by pausz** [comment]
The Brunel and Wang model was removed from the core models in TVB about 2 years ago. Unless, you really want to use this model I wouldn't recommend to code it in CUDA.

**Comment by i-Zaak** [comment]
I saw it is in the contribution director. This issue is here so that I don't forget about it, because I don't want to deal with it at first take as it is quite specific compared to the other models. We might close this later as wontfix if we decide nobody needs it.
