### ISSUE TITLE
Six's meta path importer causes deepcopy to fail

### ISSUE THREAD

**Issue by maedoc** [the-virtual-brain/tvb-library#49]

**Comment by Endle** [comment]
This [pip bug](https://bugzilla.redhat.com/show_bug.cgi?id=1173845) may be related.

**Comment by maedoc** [comment]
Can you post your trace back again here, including details of the exact command you ran, etc.

**Comment by Endle** [comment]
@maedoc commented on [2015年3月27日 GMT+8下午7:32](https://github.com/the-virtual-brain/tvb-library/issues/49#issuecomment-86906914 "2015-03-27T11:32:05Z - Replied by Github Comment Enhancer"):
> Can you post your trace back again here, including details of the exact command you ran, etc.

It's a little weird
I tried `sudo pip install scipy` on my computer(Fedora 21 64bit Workstation)
Then it failed: [Terminal Output](https://gist.github.com/Endle/797144d9e19d79573e69) [pip.log](https://gist.github.com/Endle/10cd818a6c05d14e25c0)

I'm afraid this problem related to pip would affect other problems

After that, I followed the [guide](https://cloud.sagemath.com/projects/4898b5d6-4865-41c4-af60-ae01a936b41b/files/Getting%20started%20-%20numerical%20accuracy.md)

```
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
bash Miniconda-latest-Linux-x86_64.sh
export PATH=/path/to/conda:$PATH
conda create -n tvb-gsoc numpy numexpr matplotlib scipy ipython-notebook
source activate tvb-gsoc
git clone https://github.com/the-virtual-brain/tvb-library
git clone https://github.com/the-virtual-brain/tvb-data
export PYTHONPATH=$(pwd)/tvb-data:$(pwd)/tvb-library:$PYTHONPATH
cd tvb-library
ipython notebook
```

Then, I chose `Tutorial_Anatomy_Of_A_Region_Simulation.ipynb`, and it failed
<https://gist.github.com/Endle/761008988d09c240c503>

Am I the only one who encountered this bug?

**Comment by maedoc** [comment]
I've run into a similar problem due to `meta_path` copying; I'll look into this soon.

**Comment by maedoc** [comment]
@endle can you please add `print sys.meta_path` before the [deepcopy on line 75](https://gist.github.com/Endle/761008988d09c240c503#file-tutorial_anatomy_of_a_region_simulation-log-L26), i.e.

```python
print sys.meta_path
_old_meta_path = copy.deepcopy(sys.meta_path)
```

Please attach the output; there is something being added to your meta_path which cannot be deepcopied (but this seems to be an environment dependent issue).

**Comment by Endle** [comment]
I didn't find a way to print from ipython, so I had to
``` 
+    raise Exception(len(sys.meta_path))
     _old_meta_path = copy.deepcopy(sys.meta_path)
```
Length is 1

Then
```
/home/lizhenbo/src/tvb-library/tvb/basic/profile.py in TvbProfile()
     72     env = Environment()
     73 
---> 74     raise Exception(strsys.meta_path[0])
     75     _old_meta_path = copy.deepcopy(sys.meta_path)
     76 

NameError: name 'strsys' is not defined
```

Finally
```
/home/lizhenbo/src/tvb-library/tvb/basic/profile.py in TvbProfile()
     73 
     74     obj = sys.meta_path[0]
---> 75     raise Exception(repr(obj))
     76     _old_meta_path = copy.deepcopy(sys.meta_path)
     77 

Exception: <six._SixMetaPathImporter object at 0x7f7e600a0810>
```

Do you know how to monitor the change of sys.meta_path? Thanks

**Comment by maedoc** [comment]
> <six._SixMetaPathImporter object at 0x7f7e600a0810>

This is the same object I find that causes a problem. We will implement a workaround to handle this particular class, so it shouldn't cause a problem in the future.

**Comment by Endle** [comment]
@maedoc commented on [2015年3月27日 GMT+8下午11:27](https://github.com/the-virtual-brain/tvb-library/issues/49#issuecomment-86974506 "2015-03-27T15:27:54Z - Replied by Github Comment Enhancer"):
> > 
> 
> This is the same object I find that causes a problem. We will implement a workaround to handle this particular class, so it shouldn't cause a problem in the future.

Yes, a simple hack is enough to workaround
`+ sys.meta_path = []`
Then `Tutorial_Anatomy_Of_A_Region_Simulation.ipynb` works fine

**Comment by Endle** [comment]
Thanks, @maedoc 
With <https://github.com/the-virtual-brain/tvb-library/commit/e4ba3e0e589dd16547f07bbe47632cc3ce27ec8b>, the demo runs well on my computer (Fedora 21, 64bit)
Is this a bug in [six](https://pypi.python.org/pypi/six)?

**Comment by maedoc** [comment]
Whoever wrote the meta path improter class didn't anticipate that it may be deep copied, which is perhaps reasonable assumption. 

I submitted an [upstream report](https://bitbucket.org/gutworth/six/issue/123/copying-sysmeta_path-can-fail-on)  but no response yet.

I'm closing this given we've a workaround.
