### ISSUE TITLE
`nosetests` failed

### ISSUE THREAD

**Issue by Endle** [the-virtual-brain/tvb-library#50]
I tried `nosetests` in trunk branch, and [it failed](https://gist.github.com/Endle/951ae019d740ef372c80)

How to reproduce:
```
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
bash Miniconda-latest-Linux-x86_64.sh
export PATH=/path/to/conda:$PATH
conda create -n tvb-gsoc numpy numexpr matplotlib scipy ipython-notebook
source activate tvb-gsoc
git clone https://github.com/the-virtual-brain/tvb-library
git clone https://github.com/the-virtual-brain/tvb-data
export PYTHONPATH=$(pwd)/tvb-data:$(pwd)/tvb-library:$PYTHONPATH
cd tvb-library
nosetests
```

**Comment by liadomide** [comment]
hi,

tvb is not configured for the moment for nosetests.
run tvb-library unit-tests like this:

import unittest
from tvb.tests.library.main_tests import suite as lib_suite
TEST_RUNNER = unittest.TextTestRunner()
TEST_SUITE = lib_suite()
TEST_RUNNER.run(TEST_SUITE)

regards,
lia.

**Comment by Endle** [comment]
Hi, @liadomide 
I wrote
```

import unittest
from tvb.tests.library.main_tests import suite as lib_suite
TEST_RUNNER = unittest.TextTestRunner()
TEST_SUITE = lib_suite()
TEST_RUNNER.run(TEST_SUITE)
```
in test.py, then ran `python test.py`
But still failed:
```
ERROR: test_connectivity_h5py_reload (tvb.tests.library.datatypes.connectivity_test.ConnectivityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lizhenbo/src/tvb-library/tvb/tests/library/datatypes/connectivity_test.py", line 157, in test_connectivity_h5py_reload
    conn = connectivity.Connectivity.from_file(h5_full_path)
  File "/home/lizhenbo/src/tvb-library/tvb/datatypes/connectivity.py", line 79, in from_file
    result.weights = reader.read_field("weights")
  File "/home/lizhenbo/src/tvb-library/tvb/basic/readers.py", line 73, in read_field
    raise ReaderException("Could not read from %s field" % field)
ReaderException: Could not read from weights field

----------------------------------------------------------------------
Ran 141 tests in 128.625s

FAILED (errors=1)
```

**Comment by liadomide** [comment]
Do you have tvb-data dependency https://github.com/the-virtual-brain/tvb-data ?

Regards,
Lia.

**Comment by Endle** [comment]
@liadomide 

I don't think so.
I added
```
import tvb
import tvb_data
```
in test.py, and everything is the same.

Can you reproduce it?

**Comment by liadomide** [comment]
@Endle We seem to have a dependency in one of the unit-tests towards h5py (which is not listed a requirement for tvb-library, and also not really needed).
I just marked that test to be executed only when h5py is found. Please synchronize with GitHub and retest.

I also added a helper method for launching tvb-library unit-tests in a python console:
>>> from tvb.tests import run_library
>>> run_library()

**Comment by Endle** [comment]
@liadomide Thanks. It works fine on my computer now.
Maybe this issue should be closed now?

**Comment by liadomide** [comment]
Yes. Thanks for reporting this and for your patience in testing it.
