### ISSUE TITLE
mse_analyse_region example broken

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-library#54]
Looks like because it tries to find a 'projection_eeg_1020_62.mat' matrix, which doesn't seem to exist any more ?

**Comment by maedoc** [comment]
Thanks, good catch. We're in the process of making a new default dataset, so this should be handled in the not too distant future. In the mean time, you should be able to initial the projection object with just
```python
pr = projections.ProjectionSurfaceEEG(load_default=True)
```
which will use the new EEG projection.

**Comment by JohnGriffiths** [comment]
Still having issues with this. 

Have placed notebook detailing them in a gist [here](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/anonymous/45daff305682520d1b47/raw/e0a00029ff882dcdad76006d3f42ac2157a78fc3/ISSUES_WITH_Tutorial_Evoked_Responses_In_The_Visual_Cortex.ipynb).

Please advise. 

Ta.

**Comment by liadomide** [comment]
Try to replace your tvb-data with the unziped tvb-data.zip from here: http://www.thevirtualbrain.org/tvb/zwei/ladeluke/public

**Comment by JohnGriffiths** [comment]
no effect. revised gist [here](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/anonymous/664f9704d40286cf09c6/raw/1474bebddf62615a9fae650c74667e1361849204/ISSUES_WITH_Tutorial_Evoked_Responses_In_The_Visual_Cortex_newtvbdata.ipynb). 

Are there any functioning tutorials that use the EEG projections I can compare to?

**Comment by liadomide** [comment]
are you sure you have updated with the folder I shared with you?
errors like this should no longer be present:
       No such file or directory: .....tvb_data/connectivity/connectivity_76.zip

**Comment by liadomide** [comment]
reading more through your errors: ProjectionRegionEEG is not longer present in tvb.
is your mse_analyse_region updated to the latest git version from trunk ?

**Comment by JohnGriffiths** [comment]
Yes I left that line in just to show that it was erroring.

I am working with the latest git version. 

Does the tutorial work for you without errors?

**Comment by liadomide** [comment]
- The recently shared tvb_data.zip should be installed or linked in your python site-packages as a package. Then errors like missing connectivity_76 should not longer appear.
- I think that you are using an old form of the tutorial, because ```ProjectionRegionEEG```, or ```monitors.EEG(projection_matrix_data=...)``` are being replaced on our github repo (https://github.com/the-virtual-brain/tvb-library/tree/trunk/tvb/simulator/demos) with the use of ```ProjectionSurfaceEEG``` and ```monitors.EEG(projection=..)```
- But even after those, the tutorial was still broken. A summary of the fix:

    ```
    sensors = SensorsEEG.from_file(source_file="eeg-brainstorm-65.txt")
    rm = RegionMapping(load_default=True)
    ...
    monitors.EEG(projection=pr, sensors=sensors, region_mapping=rm, period=1e3 / 4096.)
   ```
 I will soon commit a full fixed version.

**Comment by liadomide** [comment]
Have a look at commit 185c7051accbe4b2c95f6e00690f7b1023e5267c

**Comment by JohnGriffiths** [comment]
Thanks that is working now for me :)

Please let me know when I can switch back to using the tvb-data branch from the github repo, rather than the folder from the download listed above. 

Ta.

**Comment by liadomide** [comment]
Sure. We will let you know soon.
